# Aula 3

Nesta aula praticaremos a linguagem de python utilizando os pacotes Numpy e Pandas.
Aprenderemos também como utilizar o pacote "os" para explorar diretórios e arquivos.

# Numpy

In [53]:
#importando o pacote
import numpy as np

#-------------Geração de numeros aleatórios

#valores maximos e minimos
val_max,val_min = 10.,0.5
#Número de valores aleatórios
n = 1000
# Utilizando pacote numpy e função uniform que está dentro do subpacote random
array_aleatorio = np.random.uniform(val_min,val_max,n)
print(array_aleatorio)
#Utilizando pacote numpy e função randint que está dentro do subpacote random
array_aleatorio_inteiro = np.random.randint(val_min,val_max,n)
print(array_aleatorio_inteiro)

[7.02763056 1.38714878 2.33893991 6.92546702 9.42209563 5.31058511
 3.192237   1.91033599 2.19781611 0.6766731  7.13313591 6.03975616
 9.386388   7.99137402 4.46508699 7.18085447 3.9792397  1.11402928
 3.83831945 5.52509242 4.33626296 5.63201535 1.29059923 0.85675769
 3.05738908 3.49240444 0.79213638 2.04951486 1.99012379 8.76643458
 2.29968243 4.04889578 1.70410936 1.65547455 9.49203487 7.35436336
 8.47744677 7.11852249 3.04500916 7.50309369 9.5644991  8.55285424
 0.50455893 2.28331204 1.12085713 8.34907934 9.54759597 9.45940424
 6.39982615 5.39277133 1.16365002 4.29941271 5.18372348 7.33950899
 5.83167513 3.58855916 6.07179025 8.5912487  0.564642   9.26110508
 6.38989973 8.44205794 1.56246081 5.05149283 1.50946537 9.82751165
 6.24224518 0.71280916 2.37980502 8.11623076 5.59887845 4.46838596
 5.49198152 8.43813312 4.35810893 5.15386524 1.23333738 4.97383237
 4.07998607 2.18907807 2.22035598 4.83870511 4.52725784 6.1675657
 2.31847507 7.80187449 4.85454055 1.47667562 3.81462444 9.78148

In [54]:
#Verificando o tamanho da matriz arr_aleatorio
#shape
print(array_aleatorio.shape)
print(np.shape(array_aleatorio))
#size
print(array_aleatorio.size)

(1000,)
(1000,)
1000


In [55]:
#Utilizando o reshape para formatar um vetor em uma matriz 2 linhas e n colunas
mat = array_aleatorio.reshape(2,-1)
print(np.shape(mat))
print(mat)
print(mat.size)
# o colchetes duplos separa as colunas - 2 colunas com 50 valores

(2, 500)
[[7.02763056 1.38714878 2.33893991 6.92546702 9.42209563 5.31058511
  3.192237   1.91033599 2.19781611 0.6766731  7.13313591 6.03975616
  9.386388   7.99137402 4.46508699 7.18085447 3.9792397  1.11402928
  3.83831945 5.52509242 4.33626296 5.63201535 1.29059923 0.85675769
  3.05738908 3.49240444 0.79213638 2.04951486 1.99012379 8.76643458
  2.29968243 4.04889578 1.70410936 1.65547455 9.49203487 7.35436336
  8.47744677 7.11852249 3.04500916 7.50309369 9.5644991  8.55285424
  0.50455893 2.28331204 1.12085713 8.34907934 9.54759597 9.45940424
  6.39982615 5.39277133 1.16365002 4.29941271 5.18372348 7.33950899
  5.83167513 3.58855916 6.07179025 8.5912487  0.564642   9.26110508
  6.38989973 8.44205794 1.56246081 5.05149283 1.50946537 9.82751165
  6.24224518 0.71280916 2.37980502 8.11623076 5.59887845 4.46838596
  5.49198152 8.43813312 4.35810893 5.15386524 1.23333738 4.97383237
  4.07998607 2.18907807 2.22035598 4.83870511 4.52725784 6.1675657
  2.31847507 7.80187449 4.85454055 1.476

In [56]:
#Multiplicação de matrizes 
arr_resultado = array_aleatorio*array_aleatorio_inteiro
print(arr_resultado)
#mesmo shape

[56.22104452 11.0971902  18.71151926 13.85093404 56.53257376 37.1740958
 22.34565901  7.64134397  8.79126444  1.3533462  42.79881547 24.15902463
 75.09110404 15.98274805  0.          7.18085447 15.9169588   4.45611711
  7.67663889 16.57527727  8.67252591 22.52806139  6.45299616  0.
 24.45911265 10.47721332  1.58427276  8.19805943 15.92099033 70.13147663
  9.1987297  36.44006201  0.         14.89927094 75.93627895 14.70872671
 59.34212736 35.59261243  9.13502748 37.51546845 38.25799641  8.55285424
  1.00911786 20.54980838  8.96685705 41.74539669 85.92836376 66.21582971
 25.59930461 16.17831399  4.6546001  17.19765084 10.36744695 66.05558095
 34.99005077  0.          6.07179025 42.95624348  0.         64.82773557
 25.55959891  0.         12.49968645 20.20597134 13.58518836 68.79258158
 12.48449036  1.42561831  9.51922006 73.04607686 39.19214917 22.34192982
  5.49198152 33.75253249 30.50676249 41.23092195 11.10003646 19.89532949
 20.39993037  6.56723422  6.66106793 43.54834597 18.10903134

In [60]:
#multiplicação de arrays de diferente dimensões
multiplicador = np.random.randint(1,10,2)

array_resultado2 = []
for multi in multiplicador:
    print(multi)
    array_resultado2.append(array_aleatorio_inteiro*multi)
print(array_resultado2)

array_resultado2 = np.concatenate(array_resultado2)
print(array_resultado2.shape)

array_resultado3 = np.vstack(array_resultado2)
print(array_resultado3.shape)

array_resultado4 = np.hstack(array_resultado2)
print(array_resultado4.shape)

arr_resultado5 = array_resultado4.transpose()
print(arr_resultado5)

4
2
[array([32, 32, 32,  8, 24, 28, 28, 16, 16,  8, 24, 16, 32,  8,  0,  4, 16,
       16,  8, 12,  8, 16, 20,  0, 32, 12,  8, 16, 32, 32, 16, 36,  0, 36,
       32,  8, 28, 20, 12, 20, 16,  4,  8, 36, 32, 20, 36, 28, 16, 12, 16,
       16,  8, 36, 24,  0,  4, 20,  0, 28, 16,  0, 32, 16, 36, 28,  8,  8,
       16, 36, 28, 20,  4, 16, 28, 32, 36, 16, 20, 12, 12, 36, 16,  0, 16,
       28, 36,  8,  0, 32, 16, 28, 32,  8,  8,  0,  0, 12, 28, 32, 16, 20,
       12,  0, 20, 24,  0,  0, 36,  0,  8, 16, 12, 36,  8, 28, 20,  0, 32,
       24, 20,  8,  8, 36, 12,  4, 32, 20, 12, 28,  4,  4,  4, 36, 24, 36,
       20, 12, 12, 36, 36, 36, 20,  0, 24, 28,  0,  4,  8, 36,  4,  0, 20,
        8,  8,  0, 12, 20,  8, 20,  4,  4, 12, 28, 32, 32,  4, 12,  8, 28,
       36,  4, 36, 32, 12,  8,  0, 28, 36, 36, 28, 20, 32, 32, 24, 28, 28,
       20, 16, 16, 28, 20, 16, 28, 16,  4, 16,  0, 36, 20, 32, 36, 12, 36,
       16, 12, 16, 12,  4,  8,  8,  8,  8, 32, 36, 12, 28, 20, 16,  8, 28,
       36, 24, 12,  

In [61]:
array_resultado7 = np.random.rand(10,10,10)
print(array_resultado7.shape)

(10, 10, 10)


In [64]:
# acessando valores da matriz
#considerando que array resultado 7 é uma matriz temperatura com lat/lon/tempo,determine a temperatura para o tempo igual a 1em todas as latitudes e 
#longitudes
array_resultado7[:,:,0]

array([[0.21726045, 0.22515061, 0.55276252, 0.44072211, 0.05115827,
        0.6910106 , 0.53942263, 0.16716294, 0.94610212, 0.91561765],
       [0.50612658, 0.74176692, 0.52332512, 0.57219351, 0.98307675,
        0.32111307, 0.21133307, 0.1111978 , 0.14138887, 0.37111119],
       [0.03691541, 0.15364793, 0.94149724, 0.69088397, 0.06486987,
        0.51406583, 0.19361167, 0.56918126, 0.2135456 , 0.26509709],
       [0.09401139, 0.72823907, 0.30243208, 0.31011064, 0.15240396,
        0.45900802, 0.92762137, 0.85592107, 0.99166005, 0.32220956],
       [0.70737058, 0.78982755, 0.55718177, 0.09287583, 0.98459546,
        0.80911943, 0.9114501 , 0.02139308, 0.25404262, 0.73864187],
       [0.34544441, 0.54587695, 0.92558761, 0.46278635, 0.84215721,
        0.79174901, 0.80493906, 0.33643982, 0.3796873 , 0.55948187],
       [0.08727942, 0.2127842 , 0.8900805 , 0.20712318, 0.65428472,
        0.53135762, 0.4765315 , 0.20159176, 0.82143556, 0.73961896],
       [0.81186359, 0.63003398, 0.2463434

In [65]:
#para todas as longitude e primeira latitude e primeiro tempo
array_resultado7[:,0,0]

array([0.21726045, 0.50612658, 0.03691541, 0.09401139, 0.70737058,
       0.34544441, 0.08727942, 0.81186359, 0.06603038, 0.44013554])

In [66]:
#todas as lat, primeira lon, e ultimo tempo
array_resultado7[:,0,-1]

array([0.3061109 , 0.8300757 , 0.98791824, 0.05137319, 0.70059067,
       0.07976344, 0.77955477, 0.20041693, 0.9548724 , 0.83119355])

In [70]:
array_resultado7[:,0,np.shape(array_resultado7)[2]-1]#segunda dimensão

array([0.3061109 , 0.8300757 , 0.98791824, 0.05137319, 0.70059067,
       0.07976344, 0.77955477, 0.20041693, 0.9548724 , 0.83119355])

In [72]:
#Para um ponto lat lon no espaçi para todo o tempo
array_resultado7[2,2,:]

#para uma região no espaço
array_resultado7[2:4,4:6,1]

array([[0.70948463, 0.40489789],
       [0.26843448, 0.09121417]])